### ISSUE TITLE
Issue with TALOS Circle Dataset

### ISSUE THREAD

**Issue by teguhSL** [MeMory-of-MOtion/docker-loco3d#2]
While working with the TALOS circle dataset, I encountered the following issues:
1. The points on the circle are not explored thoroughly by the planner. There are gaps when I plot the initial xy locations. I attach the file here as init_location.png. 
 
![init_location](https://user-images.githubusercontent.com/7857158/55224371-a7d1a700-5210-11e9-8ca6-4c36126250c3.png)

2. For quite a few examples, there is no proper status in the 'infos.log'. The file should contain the status of the planner (success/failure), but for some cases the status file stops at q_goal. Example: the folder ce2ca8c2-6907-43b1-b566-0f684dd83368 .  I attach the log file as 'info.log' here. 

[infos.log](https://github.com/MeMory-of-MOtion/docker-loco3d/files/3022020/infos.log)

3. The phases and timesteps in the contact_sequence_trajectory.xml do not match with the one in talos_flatGround_config.csv. As explained by Pierre, one of the reasons is because in whole body trajectory the robot stays at initial configurations for 1 s, which makes the difference in the total time. 
However, even after considering this, the phases between contact sequence and whole body motion do not seem to match. That is, I started the whole body configurations from q[200:], which corresponds to starting from 1s time, but the motion does not match the supposed contact sequence in the xml file. 
Instead, I started from q[130:] (which is 0.65s), and with this the contact sequence seem to match the joint trajectory. This holds for all 10 examples that I tried. 

Would it be possible to make the two files match in terms of contact phases? for example, by segmenting the joint configurations (as well as other trajectory info not included in the xml file) into phases, so that it is easier to be processed later on.

**Comment by pFernbach** [comment]
1. Does this plot represent only the motion that was successfully generated or the the motion that was tried ? If it's the former, could you plot the initial state including for the motion that failed to generate. It is just to check if it's an issue in our sampling/size of the sample or in the motion generation. 

2. After looking at the code that write this file, this mean that the RB-planner for the root had an unexpected crash. The new release is a lot more stable and this should not happen anymore (or at least, with a very low probability).

3. The code used for the whole-body was a mess of old scripts. Even after checking I do not see why it behave like this. In the new framework the q(t) will match exactly the times for each phases in the contactSequence object. 

Do you still prefer to have a clear separation by contact phases of the whole-body trajectories, or using the times intervals from the contactSequence object is enough ? (if we guarantee that they match exactly).

**Comment by pFernbach** [comment]
I found the culprit for point 3 : 
```
    if add_stab:
      timeline0_stab = np.linspace(t0 - N_stab0 * dt_stab, t0 - dt_stab, N_stab0)
      timelinef_stab = np.linspace(tf + dt_stab, tf + N_stabf * dt_stab, N_stabf)
      timeline = np.hstack((timeline0_stab, timeline_middle, timelinef_stab))
```

Basically it add 0.5s of motion before and after the planned motion (the comments says that it's to avoid oscillation of the low level controller ...). The previously mentioned 1s of offset at the beginning is certainly not considered anymore as the two configurations are the sames.

**Comment by teguhSL** [comment]
>     1. Does this plot represent only the motion that was successfully generated or the the motion that was tried ? If it's the former, could you plot the initial state including for the motion that failed to generate. It is just to check if it's an issue in our sampling/size of the sample or in the motion generation.

The plot represents the motion which I can access the status file. The following plot include the motion without the status file (blue = normal, red = without the status file), but the gap is still there, so maybe it is the sampling that has a problem. 

![init_location_all](https://user-images.githubusercontent.com/7857158/55273326-eaa38580-52c9-11e9-918f-128350df70b0.png)


> 
>     2. After looking at the code that write this file, this mean that the RB-planner for the root had an unexpected crash. The new release is a lot more stable and this should not happen anymore (or at least, with a very low probability).

Noted, thank you!

> 3. I found the culprit for point 3 :
> 
>     if add_stab:
>       timeline0_stab = np.linspace(t0 - N_stab0 * dt_stab, t0 - dt_stab, N_stab0)
>       timelinef_stab = np.linspace(tf + dt_stab, tf + N_stabf * dt_stab, N_stabf)
>       timeline = np.hstack((timeline0_stab, timeline_middle, timelinef_stab))
> 
> Basically it add 0.5s of motion before and after the planned motion (the comments says that it's to avoid oscillation of the low level controller ...). The previously mentioned 1s of offset at the beginning is certainly not considered anymore as the two configurations are the sames.

I see. Yes, I tried to offset 0.5s and it works, thank you!

> Do you still prefer to have a clear separation by contact phases of the whole-body trajectories, or using the times intervals from the contactSequence object is enough ? (if we guarantee that they match exactly).

If you can have the clear separation in the file conveniently, I think it would be better, so that we reduce the chance of errors at later stage due to mistake in separating the phases manually. For example, if the joint trajectory is saved as python dict() or list(), according to the phases, that would be more convenient for us. 

This is also the same for the infos.log file. Do you think it is possible and convenient to save it as a python dict()? Just so that we can access the values more easily rather than to parse the text file manually.

**Comment by wxmerkt** [comment]
> This is also the same for the infos.log file. Do you think it is possible and convenient to save it as a python dict()? Just so that we can access the values more easily rather than to parse the text file manually.

Yes, please - something like this would be really helpful. Back in Deliverable 8.2 we specified to use the compressed NumPy file format (`np.savez()`) as the file format for the dataset - and this would bode very well with analysis and learning (it also loads much, much faster than a text file).

**Comment by pFernbach** [comment]
I updated the discussion https://github.com/MeMory-of-MOtion/docker-loco3d/issues/1#issuecomment-478359116 with your remarks. 

> If you can have the clear separation in the file conveniently, I think it would be better, so that we reduce the chance of errors at later stage due to mistake in separating the phases manually. For example, if the joint trajectory is saved as python dict() or list(), according to the phases, that would be more convenient for us.

I propose to still store the complete trajectory in one matrice, but have another variable to make the correspondance contact phase -> id of this matrice. Does it make sense for you ? 

For exemple, if we have a motion with three contact phases of 1s each, with a configuration size of 39 and a time step of 1ms. We would have the following : 

`
q_t.shape
`
out : (39,3000)

`
q_t[:,phase_interval[0]].shape
`
out : (39,1000)
which correspond to all the points of the trajectory for the first contact phase of the motion.

**Comment by teguhSL** [comment]
Hi @pFernbach , sorry I forgot to reply. 

> I propose to still store the complete trajectory in one matrice, but have another variable to make the correspondance contact phase -> id of this matrice. Does it make sense for you ?

If it can be ensured that the phases are consistent, I guess it is fine. 

In the current dataset, the sampling time for COM trajectory (in the contact sequence file) is different from the one in configuration trajectory, this creates potential errors when comparing the time sequences between the two. If the sampling time for future datasets are consistent then this won't be an issue.
