### ISSUE TITLE
Linked documentation "is in owner's trash"

### ISSUE THREAD

**Issue by wxmerkt** [MeMory-of-MOtion/docker-loco3d#5]
When opening the link from the README for the documentation, I get:

![image](https://user-images.githubusercontent.com/1664508/55240173-27bb3980-5230-11e9-969f-5b6b477c2671.png)

**Comment by pFernbach** [comment]
Hello, sorry that we didn't update the readme. The document have been updated and moved in the deliverables of the MEMMO project. I updated the readme with the new link and with an abstract of the information about the dataset.
