### ISSUE TITLE
Scenarios for the locomotion dataset

### ISSUE THREAD

**Issue by pFernbach** [MeMory-of-MOtion/docker-loco3d#8]
Hello, I open this issue to discuss about the scenario used to generate the motion inside the dataset. 
The proposition was to produce a first dataset with one or two simple scenario, wait a couple of weeks for feedback on the format/data/anything else and then produce a more complex dataset with other scenario. 

As mentioned in https://github.com/MeMory-of-MOtion/docker-loco3d/issues/7 the 'circle' scenario of the version 0.9 was already to long to be used as a building block. I propose this 2 simple scenario for the first release of the dataset : 

## Small circle, fixed orientation : 

The robot move of 30cm in a random direction. The goal state is in a circle of radius 30cm, with the initial state at it's center. Orientation of the origin of the robot is fixed (this will lead to strafing motion, walking backward, ect)

## Random effector motion, flat floor : 

The robot start from a random configuration with both feet in contact and move one feet to another random contact position. All contacts are co-planar with a normal along the vertical axis. 

Should we separate the cases where the vertical position of the contact changes ? Ie. one scenario where the contact are always on a ground at z=0 and another one where z is random in an interval ? 

_________________________________________

For more complex scenario we can add : 

## Random effector motion, multi-contact and non coplanar : 

The robot start from a random configuration with both feet in contact and either 0,1 or 2 hands in contact. It move one effector (choosen randomly) to another contact position. No constraints on the contact normal, which will lead to non coplanar contacts. See figure below : 

![random_contact_transition](https://user-images.githubusercontent.com/11633215/56138677-a1c12180-5f97-11e9-9dcb-4c2a8a878470.png)

top row : initial configuration, bottom row : final configuration. 
## Larger circle, without orientation constraints : 

The robot start from any point on a circle of radius 1 m and should go to the center of the circle. Final orientation is fixed, initial orientation is random, the orientation is not constrained during the motion. This will produce motions were the robot move 'forward' as much as possible, leading to motion with turns. 

## Random walk in Bauzil room : 

Initial and final position and orientation random in the environment : https://github.com/humanoid-path-planner/hpp-environments/blob/master/meshes/multicontact/bauzil_stairs.stl

In the previous framework we had to separate motion using the stairs and the others on the flat ground. We believe that our new framework can deal with both case and won't need this separation, but we need to check this.

**Comment by teguhSL** [comment]
> Small circle, fixed orientation :
> 
> The robot move of 30cm in a random direction. The goal state is in a circle of radius 30cm, with the initial state at it's center. Orientation of the origin of the robot is fixed (this will lead to strafing motion, walking backward, ect)

By origin of the robot, do you mean the root (the hip)? So the orientation of the root at the goal is also constant here?

I think this is good for starting point, but to make it a better building block, we need to include varying orientation at the goal (maybe for next dataset). 

> Random effector motion, flat floor :
> 
> The robot start from a random configuration with both feet in contact and move one feet to another random contact position. All contacts are co-planar with a normal along the vertical axis.
> 
> Should we separate the cases where the vertical position of the contact changes ? Ie. one scenario where the contact are always on a ground at z=0 and another one where z is random in an interval ?

I think this example is a better building block than the circle example, as it generalizes better. 
What I am not sure, however, if building larger motion based on this will result in a good motion overall (especially in the context of crocoddyl). If I want to create a larger motion comprising of 10 footsteps, for example, I can use this database to give me a motion for each footstep, but the motion will be moving one step, stop, moving another step, stop, etc. If the motion requires quite a dynamic movement where you need to build momentum on the first footstep to reach the second, this database will not help. In that case, we may need to add varying velocity of the root at the initial and goal contacts for this example as additional task variables (besides initial and goal contacts). But this we may want to do later, the current example is maybe sufficient for now. 

It will be better to separate movement with z = 0 and z = varying. If the aim is to use it to generate climbing stairs movement with known stairs, I think we do not really need to vary z randomly, we can choose between z = 0 and z = +- 20 cm (height of stairs). Unless we want to aim for more random environment.

**Comment by pFernbach** [comment]
> By origin of the robot, do you mean the root (the hip)? So the orientation of the root at the goal is also constant here?

Yes.

> I think this is good for starting point, but to make it a better building block, we need to include varying orientation at the goal (maybe for next dataset).

It's planned, with the scenario **Larger circle, without orientation constraints**.

> I think this example is a better building block than the circle example, as it generalizes better.
What I am not sure, however, if building larger motion based on this will result in a good motion overall (especially in the context of crocoddyl). If I want to create a larger motion comprising of 10 footsteps, for example, I can use this database to give me a motion for each footstep, but the motion will be moving one step, stop, moving another step, stop, etc. If the motion requires quite a dynamic movement where you need to build momentum on the first footstep to reach the second, this database will not help.

You are right here, this scenario will only produce motion between two static states and I don't think that this scenario should be used to learn 'walking' motion where you never go through static states. 

>In that case, we may need to add varying velocity of the root at the initial and goal contacts for this example as additional task variables (besides initial and goal contacts). But this we may want to do later, the current example is maybe sufficient for now.

We can easily add a random initial velocity with our current framework but unfortunately we cannot constraint the final velocity to be different than 0 yet. 

> It will be better to separate movement with z = 0 and z = varying. If the aim is to use it to generate climbing stairs movement with known stairs, I think we do not really need to vary z randomly, we can choose between z = 0 and z = +- 20 cm (height of stairs). Unless we want to aim for more random environment.

Noted. The stairs in the environment used are either 10cm or 15cm height. We can generate examples with +- 10 or 15 cm.

**Comment by pFernbach** [comment]
See the updated readme : https://github.com/MeMory-of-MOtion/docker-loco3d#test-scenario-description
